import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { SimObject } from "../SimObject";
import { SimRobotDrivetrain } from "./SimRobotDrivetrain";
import {
  World,
  Vec2,
  Box,
  BodyDef,
  FixtureDef,
  PrismaticJoint,
} from "planck-js";
import { IRobotSpec } from "../../specs/RobotSpecs";
import { IBaseFixtureUserData } from "../../specs/UserDataSpecs";
import { BasicSensorManager } from "./sensors/BasicSensorManager";
import { EventRegistry } from "../../EventRegistry";

const ROBOT_DEFAULT_COLOR = 0x00ff00;

/**
 * Class representing a controllable simulated robot
 *
 * This class should NEVER be instantiated outside of the Sim3D environment.
 * These objects are generated by the simulator infrastructure automatically.
 *
 * To interact with a simulated robot, use the `addRobot()` method on {@link Sim3D}
 * and use the {@link RobotHandle} that it returns.
 */
export class SimRobot extends SimObject {
  private _bodySpecs: BodyDef;
  private _fixtureSpecs: FixtureDef;

  private _drivetrain: SimRobotDrivetrain;
  private _basicSensors: BasicSensorManager;

  private _meshLoader: GLTFLoader | undefined;
  private _usingCustomMesh = false;

  constructor(spec: IRobotSpec) {
    super("SimRobot");

    if (!spec.customMesh) {
      const color =
        spec.baseColor !== undefined ? spec.baseColor : ROBOT_DEFAULT_COLOR;
      const bodyGeom = new THREE.BoxGeometry(
        spec.dimensions.x,
        spec.dimensions.y,
        spec.dimensions.z
      );
      const bodyMaterial = new THREE.MeshStandardMaterial({ color });
      const bodyMesh = new THREE.Mesh(bodyGeom, bodyMaterial);

      this._mesh = bodyMesh;
    } else {
      this._usingCustomMesh = true;
      // Set up the base mesh as a parent
      this._mesh = new THREE.Mesh();

      // TODO Longer term:
      // We should generalize the mesh loading. Potential ideas include
      // a SimCustomMeshObject that extends SimObject that knows how to
      // load meshes, and SimRobot can extend from that.
      // We might also need to slightly rework how adding a mesh to the
      // scene works, since with mesh loading, it's async. Additionally
      // if our physics geometries depend on mesh information, then that
      // will need to get deferred as well.

      // Set up the loader
      this._meshLoader = new GLTFLoader();
      this._meshLoader.load(
        spec.customMesh.filePath,
        (gltf) => {
          const loadedMesh: THREE.Group = gltf.scene;

          // Translate, Scale, rotate
          if (spec.customMesh.translation) {
            loadedMesh.position.x = spec.customMesh.translation.x;
            loadedMesh.position.y = spec.customMesh.translation.y;
            loadedMesh.position.z = spec.customMesh.translation.z;
          }
          if (spec.customMesh.scale) {
            loadedMesh.scale.x = spec.customMesh.scale.x;
            loadedMesh.scale.y = spec.customMesh.scale.y;
            loadedMesh.scale.z = spec.customMesh.scale.z;
          }
          if (spec.customMesh.rotation) {
            loadedMesh.rotation.x = spec.customMesh.rotation.x;
            loadedMesh.rotation.y = spec.customMesh.rotation.y;
            loadedMesh.rotation.z = spec.customMesh.rotation.z;
          }
          this._mesh.add(gltf.scene);
        },
        undefined,
        (err) => {
          console.error(err);
        }
      );
    }

    const bodyPos: Vec2 = new Vec2(0, 0);
    if (spec.initialPosition) {
      bodyPos.x = spec.initialPosition.x;
      bodyPos.y = spec.initialPosition.y;
    }

    this._bodySpecs = {
      type: "dynamic",
      position: bodyPos,
      angle: 0,
      linearDamping: 0.5,
      bullet: true,
      angularDamping: 0.3,
    };

    const userData: IBaseFixtureUserData = {
      selfGuid: this.guid,
      type: "robot",
    };

    this._fixtureSpecs = {
      shape: new Box(spec.dimensions.x / 2, spec.dimensions.z / 2),
      density: 1,
      isSensor: false,
      friction: 0.3,
      restitution: 0.4,
      userData: userData,
    };

    // Configure the drivetrain
    this._drivetrain = new SimRobotDrivetrain(spec, this.guid);

    // Add the created wheels as children
    this._drivetrain.wheelObjects.forEach((wheel) => {
      this.addChild(wheel);
    });

    // Configure Basic Sensors
    this._basicSensors = new BasicSensorManager(spec, this.guid);

    // Add the created sensors as children
    this._basicSensors.sensors.forEach((sensor) => {
      this.addChild(sensor);

      if (!this._usingCustomMesh && sensor.mesh) {
        sensor.mesh.translateY(-this._drivetrain.yOffset);
      }
    });

    if (!this._usingCustomMesh) {
      // Adjust our base mesh up
      this._mesh.translateY(-this._drivetrain.yOffset);
    }
  }

  update(ms: number): void {
    // This will let the drivetrain update motor forces
    this._drivetrain.update();

    this._children.forEach((childObj) => {
      childObj.update(ms);
    });

    // Update the mesh
    const bodyCenter = this._body.getWorldCenter();
    this._mesh.position.x = bodyCenter.x;
    this._mesh.position.z = bodyCenter.y;

    this._mesh.rotation.y = -this._body.getAngle();
  }

  configureFixtureLinks(world: World): void {
    this._drivetrain.wheelObjects.forEach((wheel) => {
      world.createJoint(
        new PrismaticJoint(
          {
            enableLimit: true,
            lowerTranslation: 0,
            upperTranslation: 0,
          },
          this._body,
          wheel.body,
          wheel.body.getWorldCenter(),
          new Vec2(1, 0)
        )
      );
    });

    // Configure the basic sensors
    this._basicSensors.sensors.forEach((sensor) => {
      world.createJoint(
        new PrismaticJoint(
          {
            enableLimit: true,
            lowerTranslation: 0,
            upperTranslation: 0,
          },
          this._body,
          sensor.body,
          sensor.body.getWorldCenter(),
          new Vec2(1, 0)
        )
      );
    });
  }

  registerWithEventSystem(eventRegistry: EventRegistry): void {
    this._basicSensors.registerWithEventSystem(this.guid, eventRegistry);
  }

  // External facing API
  setMotorPower(channel: number, value: number): void {
    this._drivetrain.setMotorPower(channel, value);
  }

  getDigitalInput(channel: number): boolean {
    return this._basicSensors.getDigitalInput(channel);
  }

  getAnalogInput(channel: number): number {
    return this._basicSensors.getAnalogInput(channel);
  }

  getBodySpecs(): BodyDef {
    return this._bodySpecs;
  }

  getFixtureDef(): FixtureDef {
    return this._fixtureSpecs;
  }
}
